import csv
import json
import uuid
from urllib.error import URLError
from urllib.request import Request, urlopen
from pathlib import Path
from typing import List, Literal

from dotenv import load_dotenv
load_dotenv()

from fastapi import Depends, FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.orm import Session

import os
import smtplib
from email.mime.text import MIMEText
import random
from datetime import datetime, timedelta, timezone

try:
    from .auth import get_current_user
except ImportError:
    from auth import get_current_user

try:
    from .database import engine, get_db
    from .models import (
        CartItem,
        CommentLike,
        FarmerCheckin,
        Favorite,
        ForecastPriceAlert,
        ListingUnitOption,
        Moment,
        MomentComment,
        MomentLike,
        Order,
        OrderItem,
        PendingRegistration,
        PriceAlertNotification,
        PriceHistory,
        PricePrediction,
        ProduceListing,
        Review,
        User,
    )
except ImportError:
    from database import engine, get_db
    from models import (
        CartItem,
        CommentLike,
        FarmerCheckin,
        Favorite,
        ForecastPriceAlert,
        ListingUnitOption,
        Moment,
        MomentComment,
        MomentLike,
        Order,
        OrderItem,
        PendingRegistration,
        PriceAlertNotification,
        PriceHistory,
        PricePrediction,
        ProduceListing,
        Review,
        User,
    )

app  = FastAPI(title="Theraprice Backend API")
app.add_middleware(
    CORSMiddleware,
    # Local frontend development servers (React and VS Code Live Server).
    # Add the deployed frontend origin here before production release.
    allow_origins=["http://localhost:3000", "http://localhost:5000", "http://127.0.0.1:5000", "http://localhost:5500", "http://127.0.0.1:5500"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

try:
    from .database import Base
except ImportError:
    from database import Base

Base.metadata.create_all(bind=engine)


# Forecast artifacts are generated by model/production_pipeline.py.  They are
# deliberately read from disk rather than copied into PricePrediction: the
# latter is an application table, while these files retain the model interval,
# reliability score, provenance, and explanation needed by the forecast UI.
PROJECT_DIR = Path(__file__).resolve().parent.parent
MODEL_DIR = PROJECT_DIR / "model"
MODEL_DATA_DIR = MODEL_DIR / "data"
MODEL_FORECAST_DIR = MODEL_DIR / "production_output" / "forecasts"
MODEL_ARTIFACT_DIR = MODEL_DIR / "production_output" / "models"


def _available_model_crops() -> dict[str, str]:
    """Return case-insensitive crop lookup keys mapped to safe file stems."""
    return {path.stem.lower(): path.stem for path in MODEL_DATA_DIR.glob("*.csv")}


def _forecast_rows(path: Path) -> list[dict]:
    if not path.is_file():
        raise HTTPException(
            status_code=503,
            detail="Forecast artifacts are unavailable. Run model/production_pipeline.py first.",
        )
    with path.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    number_fields = {
        "horizon_months", "predicted_price", "lower_80", "upper_80",
        "confidence_score_percent", "interval_confidence_percent", "days_covered",
        "year", "months_covered", "avg_predicted_price", "avg_lower_80",
        "avg_upper_80", "min_predicted_price", "max_predicted_price",
    }
    for row in rows:
        for field in number_fields.intersection(row):
            value = row[field]
            if value == "":
                row[field] = None
            elif field in {"horizon_months", "days_covered", "year", "months_covered", "interval_confidence_percent"}:
                row[field] = int(float(value))
            else:
                row[field] = float(value)
        if "partial_year" in row:
            row["partial_year"] = row["partial_year"].strip().lower() == "true"
    return rows


def _model_summary(stem: str) -> dict:
    path = MODEL_ARTIFACT_DIR / f"{stem}_model.json"
    if not path.is_file():
        return {}
    with path.open(encoding="utf-8") as handle:
        artifact = json.load(handle)
    return {
        "summary": artifact.get("summary", {}),
        "view_notes": artifact.get("view_notes", {}),
    }


@app.get("/forecast/crops")
def get_forecast_crops():
    """List crops with generated model forecasts and the supported views."""
    crops = []
    for stem in sorted(set(_available_model_crops().values())):
        summary = _model_summary(stem).get("summary", {})
        crops.append(
            {
                "crop": stem,
                "available_frequencies": ["daily", "weekly", "monthly", "yearly"],
                "training_end": summary.get("training_end"),
                "test_wape": summary.get("test_wape"),
            }
        )
    return crops


@app.get("/forecast/{crop_name}")
def get_model_forecast(
    crop_name: str,
    frequency: Literal["daily", "weekly", "monthly", "yearly"] = Query(default="monthly"),
    include_history: bool = Query(default=False),
):
    """Serve a model forecast and, optionally, its observed monthly history.

    Daily and weekly response rows include `source_frequency` so clients can
    clearly disclose that they are display views derived from the monthly
    model, not independently validated high-frequency forecasts.
    """
    crops = _available_model_crops()
    stem = crops.get(crop_name.strip().lower())
    if stem is None:
        raise HTTPException(status_code=404, detail=f"No model data found for crop '{crop_name}'.")
    filename = f"{stem}_{frequency}_future.csv" if frequency != "monthly" else f"{stem}_future.csv"
    summary = _model_summary(stem)
    response = {
        "commodity": stem,
        "frequency": frequency,
        "data_scope": "Monthly commodity series; no city-level data is currently available.",
        "forecast": _forecast_rows(MODEL_FORECAST_DIR / filename),
        "model": summary.get("summary", {}),
        "view_notes": summary.get("view_notes", {}),
    }
    if include_history:
        with (MODEL_DATA_DIR / f"{stem}.csv").open(newline="", encoding="utf-8") as handle:
            response["history"] = [
                {"date": row["date"], "price": float(row["value"]), "is_predicted": False}
                for row in csv.DictReader(handle)
            ]
    return response


class ForecastAlertCreate(BaseModel):
    user_id: str
    crop_name: str
    threshold_price: float
    direction: Literal["above", "below"]
    frequency: Literal["daily", "weekly", "monthly"] = "daily"


def _forecast_filename(stem: str, frequency: str) -> str:
    return f"{stem}_future.csv" if frequency == "monthly" else f"{stem}_{frequency}_future.csv"


def _threshold_crossing(alert: ForecastPriceAlert) -> dict | None:
    """Return the first future model row satisfying an active alert."""
    rows = _forecast_rows(MODEL_FORECAST_DIR / _forecast_filename(alert.crop_name, alert.frequency))
    threshold = float(alert.threshold_price)
    for row in rows:
        price = float(row["predicted_price"])
        if (alert.direction == "above" and price >= threshold) or (
            alert.direction == "below" and price <= threshold
        ):
            return row
    return None


def _trigger_alert(alert: ForecastPriceAlert, crossing: dict, db: Session) -> None:
    alert.active = False
    alert.triggered_at = datetime.now(timezone.utc)
    comparison = "reached or exceeded" if alert.direction == "above" else "reached or fell below"
    # Some existing frontend sessions identify users by phone rather than the
    # database UUID. Keep the threshold alert itself, and create an in-app
    # notification only once we have a matching persisted user record.
    if db.query(User).filter(User.id == alert.user_id).first() is not None:
        db.add(
            PriceAlertNotification(
            id=str(uuid.uuid4()),
            user_id=alert.user_id,
            title="Forecast price alert",
            message=(
                f"{alert.crop_name} is forecast at {float(crossing['predicted_price']):,.0f} FCFA "
                f"on {crossing.get('date', crossing.get('week_start'))}; it has {comparison} "
                f"your {float(alert.threshold_price):,.0f} FCFA threshold."
            ),
            crop_type=alert.crop_name,
            type="price_surge" if alert.direction == "above" else "price_drop",
            read=False,
            )
        )


@app.post("/forecast-alerts", status_code=201)
def create_forecast_alert(payload: ForecastAlertCreate, db: Session = Depends(get_db)):
    crops = _available_model_crops()
    stem = crops.get(payload.crop_name.strip().lower())
    if stem is None:
        raise HTTPException(status_code=404, detail=f"No model data found for crop '{payload.crop_name}'.")
    if payload.threshold_price <= 0:
        raise HTTPException(status_code=422, detail="threshold_price must be positive.")
    alert = ForecastPriceAlert(
        id=str(uuid.uuid4()),
        user_id=payload.user_id,
        crop_name=stem,
        threshold_price=payload.threshold_price,
        direction=payload.direction,
        frequency=payload.frequency,
        active=True,
    )
    crossing = _threshold_crossing(alert)
    if crossing is not None:
        _trigger_alert(alert, crossing, db)
    db.add(alert)
    db.commit()
    return {
        "alert_id": alert.id,
        "active": alert.active,
        "triggered": crossing is not None,
        "crossing": crossing,
    }


@app.get("/forecast-alerts/{user_id}")
def get_forecast_alerts(user_id: str, db: Session = Depends(get_db)):
    alerts = db.query(ForecastPriceAlert).filter(ForecastPriceAlert.user_id == user_id).all()
    return [serialize_model(alert) for alert in alerts]


@app.post("/forecast-alerts/evaluate")
def evaluate_forecast_alerts(db: Session = Depends(get_db)):
    """Evaluate active alerts after a forecast refresh (safe to call from a scheduler)."""
    triggered = []
    for alert in db.query(ForecastPriceAlert).filter(ForecastPriceAlert.active.is_(True)).all():
        crossing = _threshold_crossing(alert)
        if crossing is not None:
            _trigger_alert(alert, crossing, db)
            triggered.append({"alert_id": alert.id, "crossing": crossing})
    db.commit()
    return {"triggered": triggered, "count": len(triggered)}


def serialize_model(model) -> dict:
    return {column.name: getattr(model, column.name) for column in model.__table__.columns}


@app.get("/")
def read_root():
    return {"status": "Theraprice backend is running"}


@app.get("/health")
def health_check():
    return {"status": "ok"}


@app.get("/products")
def get_products(db: Session = Depends(get_db), limit: int = Query(default=100, ge=1)):
    try:
        products = db.query(ProduceListing).order_by(ProduceListing.created_at.desc()).limit(limit).all()
        return [serialize_model(item) for item in products]
    except SQLAlchemyError:
        return []


class ProductCreate(BaseModel):
    title: str
    category: str
    unit: str
    price_xaf: int
    description: str = ""
    image_url: str | None = None
    quantity_available: int = 1


LISTING_CATEGORY_MAP = {
    "vegetables": "Vegetables",
    "plantains & tubers": "Tubers",
    "tubers": "Tubers",
    "fruits": "Fruits",
    "spices & herbs": "Spices",
    "spices": "Spices",
    "grains & cereals": "Grains",
    "grains": "Grains",
}


@app.post("/products", status_code=201)
def create_product(
    payload: ProductCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    if current_user.role != "farmer":
        raise HTTPException(403, "Only farmer accounts can create product listings")
    if not payload.title.strip() or payload.price_xaf <= 0 or payload.quantity_available <= 0:
        raise HTTPException(400, "Product title, price, and quantity must be positive")
    category = LISTING_CATEGORY_MAP.get(payload.category.strip().lower())
    if not category:
        raise HTTPException(400, "Choose one of: Vegetables, Tubers, Fruits, Spices, or Grains")
    listing = ProduceListing(
        id=str(uuid.uuid4()),
        farmer_id=current_user.id,
        title=payload.title.strip(),
        crop_type=payload.title.strip(),
        category=category,
        price_xaf=payload.price_xaf,
        unit=payload.unit.strip(),
        quantity_available=payload.quantity_available,
        region=(current_user.location or "").split(",")[0].strip() or "Unknown",
        image_url=payload.image_url,
        description=payload.description.strip(),
        quality_grade="Standard",
        size="Medium",
        is_fresh=True,
        verification_status="pending",
    )
    try:
        db.add(listing)
        db.commit()
        db.refresh(listing)
        return serialize_model(listing)
    except SQLAlchemyError as exc:
        db.rollback()
        raise HTTPException(500, "Unable to save this product listing. Please try again.") from exc


@app.get("/users")
def get_users(db: Session = Depends(get_db), limit: int = Query(default=100, ge=1)):
    try:
        users = db.query(User).order_by(User.created_at.desc()).limit(limit).all()
        return [serialize_model(item) for item in users]
    except SQLAlchemyError:
        return []


@app.get("/predictions/{crop_name}")
def get_prediction(crop_name: str, db: Session = Depends(get_db)):
    try:
        result = db.query(PricePrediction).filter(PricePrediction.crop_name == crop_name).all()
        return [serialize_model(item) for item in result]
    except SQLAlchemyError:
        return []


@app.get("/products/{product_id}")
def get_product(product_id: str, db: Session = Depends(get_db)):
    try:
        product = db.query(ProduceListing).filter(ProduceListing.id == product_id).first()
        if not product:
            return {"error": "Product not found"}
        return serialize_model(product)
    except SQLAlchemyError:
        return {"error": "Product not found"}


@app.get("/farmers/{farmer_id}")
def get_farmer(farmer_id: str, db: Session = Depends(get_db)):
    try:
        farmer = db.query(User).filter(User.id == farmer_id, User.role == "farmer").first()
        if not farmer:
            return {"error": "Farmer not found"}
        return serialize_model(farmer)
    except SQLAlchemyError:
        return {"error": "Farmer not found"}


@app.get("/moments")
def get_moments(db: Session = Depends(get_db), limit: int = Query(default=100, ge=1)):
    try:
        moments = db.query(Moment).order_by(Moment.created_at.desc()).limit(limit).all()
        return [serialize_model(item) for item in moments]
    except SQLAlchemyError:
        return []


@app.get("/reviews")
def get_reviews(db: Session = Depends(get_db), limit: int = Query(default=100, ge=1)):
    try:
        reviews = db.query(Review).order_by(Review.created_at.desc()).limit(limit).all()
        return [serialize_model(item) for item in reviews]
    except SQLAlchemyError:
        return []


@app.get("/price-history/{crop_name}")
def get_price_history(crop_name: str, db: Session = Depends(get_db), region: str = Query(default="Yaoundé")):
    try:
        history = db.query(PriceHistory).filter(
            PriceHistory.crop_name == crop_name,
            PriceHistory.region == region,
        ).order_by(PriceHistory.id.asc()).all()
        return [serialize_model(item) for item in history]
    except SQLAlchemyError:
        return []


@app.get("/checkins/{farmer_id}")
def get_checkins(farmer_id: str, db: Session = Depends(get_db)):
    try:
        checkins = db.query(FarmerCheckin).filter(FarmerCheckin.farmer_id == farmer_id).all()
        return [serialize_model(item) for item in checkins]
    except SQLAlchemyError:
        return []


@app.get("/alerts/{user_id}")
def get_alerts(user_id: str, db: Session = Depends(get_db)):
    try:
        alerts = db.query(PriceAlertNotification).filter(PriceAlertNotification.user_id == user_id).all()
        return [serialize_model(item) for item in alerts]
    except SQLAlchemyError:
        return []


class OrderItemCreate(BaseModel):
    listing_id: str
    quantity: int
    price_xaf_at_purchase: int


class OrderCreate(BaseModel):
    buyer_id: str
    farmer_id: str
    total_amount_xaf: int
    subtotal_xaf: int
    payment_method: str
    payment_phone: str
    delivery_address: str
    region: str
    transaction_ref: str
    items: List[OrderItemCreate]
    delivery_fee_xaf: int = 1500


def _get_confirmed_deposit(deposit_id: str) -> dict:
    """Ask the isolated payment service for an authoritative deposit status."""
    internal_key = os.getenv("PAYMENT_INTERNAL_KEY")
    if not internal_key:
        raise HTTPException(503, "Payment verification service is not configured")
    service_url = os.getenv("PAYMENT_SERVICE_URL", "http://127.0.0.1:5000/api/payment")
    request = Request(
        f"{service_url}/internal/deposits/{deposit_id}",
        headers={"x-payment-internal-key": internal_key},
        method="GET",
    )
    try:
        with urlopen(request, timeout=35) as response:
            payload = json.loads(response.read().decode("utf-8"))
    except (URLError, TimeoutError) as exc:
        raise HTTPException(503, "Payment verification service is unavailable") from exc
    if payload.get("status") != "COMPLETED":
        raise HTTPException(409, "Payment has not been completed")
    return payload


@app.post("/orders", status_code=201)
def create_order(
    order: OrderCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    try:
        if order.buyer_id != current_user.id:
            raise HTTPException(status_code=403, detail="Orders can only be created for the authenticated buyer")
        if order.subtotal_xaf < 0 or order.delivery_fee_xaf < 0:
            raise HTTPException(status_code=400, detail="Order amounts cannot be negative")
        if order.total_amount_xaf != order.subtotal_xaf + order.delivery_fee_xaf:
            raise HTTPException(status_code=400, detail="Total must equal subtotal plus delivery fee")

        # Never trust a browser-supplied transaction reference: pawaPay must
        # report the deposit as completed before escrow is marked as paid.
        _get_confirmed_deposit(order.transaction_ref)

        # The delivery charge is not part of the farmer's produce proceeds.
        # Of the produce subtotal: 40% is the initial farmer release, 57% is
        # reserved for buyer-confirmed delivery, and the remaining 3% is the
        # Theraprice platform fee. Assign rounding residue to the final payout.
        farmer_40 = round(order.subtotal_xaf * 0.40)
        platform_fee = round(order.subtotal_xaf * 0.03)
        farmer_57 = order.subtotal_xaf - farmer_40 - platform_fee
        order_id = str(uuid.uuid4())
        new_order = Order(
            id=order_id,
            buyer_id=order.buyer_id,
            farmer_id=order.farmer_id,
            subtotal_xaf=order.subtotal_xaf,
            delivery_fee_xaf=order.delivery_fee_xaf,
            platform_escrow_fee_xaf=platform_fee,
            farmer_40_amount_xaf=farmer_40,
            farmer_57_amount_xaf=farmer_57,
            total_amount_xaf=order.total_amount_xaf,
            payment_method=order.payment_method,
            payment_phone=order.payment_phone,
            payment_status="paid_escrow",
            order_status="confirmed",
            escrow_status="held_in_escrow",
            delivery_address=order.delivery_address,
            region=order.region,
            estimated_delivery_days=3,
            transaction_ref=order.transaction_ref,
            status="Placed",
        )
        db.add(new_order)

        for item in order.items:
            db.add(
                OrderItem(
                    order_id=order_id,
                    listing_id=item.listing_id,
                    quantity=item.quantity,
                    price_xaf_at_purchase=item.price_xaf_at_purchase,
                    unit_at_purchase="kg",
                )
            )

        db.commit()
        return {
            "order_id": order_id,
            "status": "created",
            "escrow": {
                "farmer_40_amount_xaf": farmer_40,
                "farmer_57_amount_xaf": farmer_57,
                "platform_fee_xaf": platform_fee,
                "delivery_fee_xaf": order.delivery_fee_xaf,
            },
        }
    except SQLAlchemyError:
        db.rollback()
        return {"status": "error", "message": "Unable to create order"}


class PayoutRecipient(BaseModel):
    provider: str = "MTN_MOMO_CMR"


def _start_farmer_payout(order: Order, amount: int, farmer_phone: str, provider: str, phase: str) -> str:
    """Ask the isolated payment service to send a payout; never expose it to browsers."""
    internal_key = os.getenv("PAYMENT_INTERNAL_KEY")
    if not internal_key:
        raise HTTPException(503, "Payout service is not configured")
    service_url = os.getenv("PAYMENT_SERVICE_URL", "http://127.0.0.1:5000/api/payment")
    body = json.dumps({
        "phone": farmer_phone,
        "amount": amount,
        "provider": provider,
        "orderId": order.id,
        "phase": phase,
    }).encode("utf-8")
    request = Request(
        f"{service_url}/internal/payout",
        data=body,
        headers={"Content-Type": "application/json", "x-payment-internal-key": internal_key},
        method="POST",
    )
    try:
        with urlopen(request, timeout=35) as response:
            payload = json.loads(response.read().decode("utf-8"))
    except (URLError, TimeoutError) as exc:
        raise HTTPException(503, "Payout service is unavailable") from exc
    if payload.get("status") == "REJECTED" or not payload.get("payoutId"):
        raise HTTPException(502, payload.get("error", "Payout was rejected"))
    return payload["payoutId"]


@app.post("/orders/{order_id}/release-initial")
def release_initial_farmer_payment(
    order_id: str,
    recipient: PayoutRecipient,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Farmer acceptance releases exactly 40% of the produce subtotal."""
    order = db.query(Order).filter(Order.id == order_id).first()
    if not order:
        raise HTTPException(404, "Order not found")
    if order.farmer_id != current_user.id:
        raise HTTPException(403, "Only the assigned farmer can accept this order")
    if order.farmer_40_payout_ref:
        return {"order_id": order.id, "payout_ref": order.farmer_40_payout_ref, "already_started": True}
    payout_ref = _start_farmer_payout(order, order.farmer_40_amount_xaf, current_user.phone, recipient.provider, "farmer_40")
    order.farmer_40_payout_ref = payout_ref
    db.commit()
    return {"order_id": order.id, "payout_ref": payout_ref, "amount_xaf": order.farmer_40_amount_xaf}


@app.post("/orders/{order_id}/confirm-delivery")
def confirm_delivery_and_release_final_payment(
    order_id: str,
    recipient: PayoutRecipient,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Buyer delivery confirmation releases only the reserved 57% farmer payout."""
    order = db.query(Order).filter(Order.id == order_id).first()
    if not order:
        raise HTTPException(404, "Order not found")
    if order.buyer_id != current_user.id:
        raise HTTPException(403, "Only the buyer can confirm delivery")
    if not order.farmer_40_payout_ref:
        raise HTTPException(409, "The farmer's 40% release has not been initiated")
    if order.farmer_57_payout_ref:
        return {"order_id": order.id, "payout_ref": order.farmer_57_payout_ref, "already_started": True}
    farmer = db.query(User).filter(User.id == order.farmer_id).first()
    if not farmer:
        raise HTTPException(409, "The assigned farmer has no payout account")
    payout_ref = _start_farmer_payout(order, order.farmer_57_amount_xaf, farmer.phone, recipient.provider, "farmer_57")
    order.farmer_57_payout_ref = payout_ref
    order.delivery_confirmed_by_buyer = True
    order.order_status = "delivered"
    order.status = "Delivered"
    order.escrow_status = "released_to_farmer"
    db.commit()
    return {"order_id": order.id, "payout_ref": payout_ref, "amount_xaf": order.farmer_57_amount_xaf, "platform_fee_xaf": order.platform_escrow_fee_xaf}


class CartItemCreate(BaseModel):
    user_id: str
    listing_id: str
    quantity: int


@app.get("/cart/{user_id}")
def get_cart(user_id: str, db: Session = Depends(get_db)):
    try:
        items = db.query(CartItem).filter(CartItem.user_id == user_id).all()
        return [serialize_model(item) for item in items]
    except SQLAlchemyError:
        return []


@app.post("/cart")
def add_to_cart(item: CartItemCreate, db: Session = Depends(get_db)):
    try:
        existing = db.query(CartItem).filter(
            CartItem.user_id == item.user_id,
            CartItem.listing_id == item.listing_id,
        ).first()

        if existing:
            existing.quantity = item.quantity
        else:
            db.add(CartItem(user_id=item.user_id, listing_id=item.listing_id, quantity=item.quantity))

        db.commit()
        return {"status": "ok"}
    except SQLAlchemyError:
        db.rollback()
        return {"status": "error", "message": "Unable to update cart"}


@app.delete("/cart/{user_id}/{listing_id}")
def remove_from_cart(user_id: str, listing_id: str, db: Session = Depends(get_db)):
    try:
        item = db.query(CartItem).filter(
            CartItem.user_id == user_id,
            CartItem.listing_id == listing_id,
        ).first()
        if item:
            db.delete(item)
            db.commit()
        return {"status": "removed"}
    except SQLAlchemyError:
        db.rollback()
        return {"status": "error", "message": "Unable to remove cart item"}


@app.get("/favorites/{user_id}")
def get_favorites(user_id: str, db: Session = Depends(get_db)):
    try:
        favorites = db.query(Favorite).filter(Favorite.user_id == user_id).all()
        return [serialize_model(item) for item in favorites]
    except SQLAlchemyError:
        return []


@app.get("/listing-options/{listing_id}")
def get_listing_options(listing_id: str, db: Session = Depends(get_db)):
    try:
        options = db.query(ListingUnitOption).filter(ListingUnitOption.listing_id == listing_id).all()
        return [serialize_model(item) for item in options]
    except SQLAlchemyError:
        return []


@app.post("/listing-options", status_code=201)
def create_listing_option(payload: dict, db: Session = Depends(get_db)):
    try:
        option = ListingUnitOption(
            id=str(uuid.uuid4()),
            listing_id=payload.get("listing_id"),
            unit=payload.get("unit"),
            price_xaf=payload.get("price_xaf"),
        )
        db.add(option)
        db.commit()
        return {"status": "created", "option_id": option.id}
    except SQLAlchemyError:
        db.rollback()
        return {"status": "error", "message": "Unable to create listing option"}


@app.post("/favorites", status_code=201)
def add_favorite(payload: dict, db: Session = Depends(get_db)):
    try:
        favorite = Favorite(user_id=payload.get("user_id"), listing_id=payload.get("listing_id"))
        db.add(favorite)
        db.commit()
        return {"status": "added"}
    except SQLAlchemyError:
        db.rollback()
        return {"status": "error", "message": "Unable to add favorite"}


@app.post("/reviews", status_code=201)
def create_review(payload: dict, db: Session = Depends(get_db)):
    try:
        review = Review(
            id=str(uuid.uuid4()),
            farmer_id=payload.get("farmer_id"),
            buyer_id=payload.get("buyer_id"),
            buyer_name=payload.get("buyer_name"),
            rating=payload.get("rating"),
            comment=payload.get("comment"),
            listing_id=payload.get("listing_id"),
        )
        db.add(review)
        db.commit()
        return {"status": "created", "review_id": review.id}
    except SQLAlchemyError:
        db.rollback()
        return {"status": "error", "message": "Unable to create review"}


@app.post("/checkins", status_code=201)
def create_checkin(payload: dict, db: Session = Depends(get_db)):
    try:
        checkin = FarmerCheckin(
            id=str(uuid.uuid4()),
            farmer_id=payload.get("farmer_id"),
            crop_type=payload.get("crop_type"),
            crop_stage=payload.get("crop_stage"),
            expected_harvest_qty=payload.get("expected_harvest_qty"),
            expected_harvest_date=payload.get("expected_harvest_date"),
            location=payload.get("location"),
        )
        db.add(checkin)
        db.commit()
        return {"status": "created", "checkin_id": checkin.id}
    except SQLAlchemyError:
        db.rollback()
        return {"status": "error", "message": "Unable to create checkin"}


@app.post("/alerts", status_code=201)
def create_alert(payload: dict, db: Session = Depends(get_db)):
    try:
        alert = PriceAlertNotification(
            id=str(uuid.uuid4()),
            user_id=payload.get("user_id"),
            title=payload.get("title"),
            message=payload.get("message"),
            crop_type=payload.get("crop_type"),
            type=payload.get("type"),
            read=False,
        )
        db.add(alert)
        db.commit()
        return {"status": "created", "alert_id": alert.id}
    except SQLAlchemyError:
        db.rollback()
        return {"status": "error", "message": "Unable to create alert"}


@app.get("/moments/{moment_id}/comments")
def get_moment_comments(moment_id: str, db: Session = Depends(get_db)):
    try:
        comments = db.query(MomentComment).filter(MomentComment.moment_id == moment_id).all()
        return [serialize_model(item) for item in comments]
    except SQLAlchemyError:
        return []


@app.post("/moments/{moment_id}/comments", status_code=201)
def create_moment_comment(moment_id: str, payload: dict, db: Session = Depends(get_db)):
    try:
        comment = MomentComment(
            id=str(uuid.uuid4()),
            moment_id=moment_id,
            buyer_name=payload.get("buyer_name"),
            comment=payload.get("comment"),
        )
        db.add(comment)
        db.commit()
        return {"status": "created", "comment_id": comment.id}
    except SQLAlchemyError:
        db.rollback()
        return {"status": "error", "message": "Unable to create comment"}


@app.get("/moments/{moment_id}/likes")
def get_moment_likes(moment_id: str, db: Session = Depends(get_db)):
    try:
        likes = db.query(MomentLike).filter(MomentLike.moment_id == moment_id).all()
        return [serialize_model(item) for item in likes]
    except SQLAlchemyError:
        return []


@app.post("/moments/{moment_id}/like", status_code=201)
def like_moment(moment_id: str, payload: dict, db: Session = Depends(get_db)):
    try:
        like = MomentLike(user_id=payload.get("user_id"), moment_id=moment_id)
        db.add(like)
        db.commit()
        return {"status": "liked"}
    except SQLAlchemyError:
        db.rollback()
        return {"status": "error", "message": "Unable to like moment"}


from fastapi import Depends, HTTPException, status
from pydantic import BaseModel, EmailStr
import uuid

from .auth import hash_password, verify_password, create_access_token, get_current_user
from .models import User
from .database import get_db
from sqlalchemy.orm import Session


# --- Request schemas ---
class RegisterRequest(BaseModel):
    name: str
    phone: str
    email: EmailStr | None = None
    password: str
    role: str          # "farmer" or "buyer"
    location: str

class LoginRequest(BaseModel):
    phone: str
    password: str


# --- Register ---
@app.post("/register")
def register(payload: RegisterRequest, db: Session = Depends(get_db)):
    existing_phone = db.query(User).filter(User.phone == payload.phone).first()
    if existing_phone:
        raise HTTPException(status_code=400, detail="Phone number is already registered. Please log in.")
    if not payload.email:
        raise HTTPException(status_code=400, detail="An email address is required for verification")
    if db.query(User).filter(User.email == payload.email).first():
        raise HTTPException(status_code=400, detail="Email already registered")

    pending = db.query(PendingRegistration).filter(PendingRegistration.phone == payload.phone).first()
    if pending:
        pending_with_email = db.query(PendingRegistration).filter(
            PendingRegistration.email == payload.email,
            PendingRegistration.phone != payload.phone,
        ).first()
        if pending_with_email:
            raise HTTPException(status_code=400, detail="A verification is already pending for this email address")
        # This is not an account yet, so allow the person to restart an
        # unfinished registration with corrected contact details/password.
        pending.name, pending.email, pending.role, pending.location = payload.name, payload.email, payload.role, payload.location
        pending.password_hash = hash_password(payload.password)
        pending.otp_code = None
        pending.otp_expires_at = None
    else:
        if db.query(PendingRegistration).filter(PendingRegistration.email == payload.email).first():
            raise HTTPException(status_code=400, detail="A verification is already pending for this email address")
        pending = PendingRegistration(phone=payload.phone, name=payload.name, email=payload.email, password_hash=hash_password(payload.password), role=payload.role, location=payload.location)
        db.add(pending)
    db.commit()
    return {"status": "pending_verification", "phone": pending.phone, "email": pending.email}


# --- Login ---
@app.post("/login")
def login(payload: LoginRequest, db: Session = Depends(get_db)):
    user = db.query(User).filter(User.phone == payload.phone).first()
    if not user or not user.password_hash or not verify_password(payload.password, user.password_hash):
        raise HTTPException(status_code=401, detail="Invalid phone or password")

    token = create_access_token(data={"sub": user.id, "role": user.role})
    return {"access_token": token, "token_type": "bearer", "id": user.id, "name": user.name, "role": user.role}

@app.get("/me")
def read_current_user(current_user: User = Depends(get_current_user)):
    return {
        "id": current_user.id,
        "name": current_user.name,
        "phone": current_user.phone,
        "role": current_user.role,
        "verification_status": current_user.verification_status,
    }  

from pydantic import BaseModel

class SendOtpRequest(BaseModel):
    phone: str
    channel: Literal["email", "sms"] = "email"

class VerifyOtpRequest(BaseModel):
    phone: str
    otp_code: str

def send_otp_email(to_email: str, otp_code: str):
    sender = os.getenv("EMAIL_ADDRESS")
    password = os.getenv("EMAIL_APP_PASSWORD")

    msg = MIMEText(f"Your Theraprice verification code is: {otp_code}\n\nThis code expires in 10 minutes.")
    msg["Subject"] = "Your Theraprice verification code"
    msg["From"] = sender
    msg["To"] = to_email

    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.starttls()
        server.login(sender, password)
        server.send_message(msg)    


@app.post("/send-otp")
def send_otp(payload: SendOtpRequest, db: Session = Depends(get_db)):
    pending = db.query(PendingRegistration).filter(PendingRegistration.phone == payload.phone).first()
    if not pending:
        raise HTTPException(status_code=404, detail="No pending registration found")

    code = str(random.randint(100000, 999999))  # 6-digit code
    pending.otp_code = code
    pending.otp_expires_at = datetime.now(timezone.utc) + timedelta(minutes=10)
    db.commit()

    if payload.channel == "sms":
        # An SMS gateway is not configured for this project yet. Do not claim
        # that a code was sent when it cannot be delivered.
        raise HTTPException(status_code=503, detail="SMS verification is not configured. Select email verification.")

    try:
        send_otp_email(pending.email, code)
    except (OSError, smtplib.SMTPException) as exc:
        raise HTTPException(status_code=503, detail="OTP email could not be sent. Check EMAIL_ADDRESS and EMAIL_APP_PASSWORD.") from exc

    return {"message": "OTP sent"}


@app.post("/verify-otp")
def verify_otp(payload: VerifyOtpRequest, db: Session = Depends(get_db)):
    pending = db.query(PendingRegistration).filter(PendingRegistration.phone == payload.phone).first()
    if not pending or not pending.otp_code:
        raise HTTPException(status_code=400, detail="No OTP requested for this registration")

    if datetime.now(timezone.utc) > pending.otp_expires_at:
        raise HTTPException(status_code=400, detail="OTP expired")

    if payload.otp_code != pending.otp_code:
        raise HTTPException(status_code=400, detail="Invalid OTP")

    # OTP correct — clear it so it can't be reused
    if db.query(User).filter(User.phone == pending.phone).first():
        raise HTTPException(status_code=409, detail="Phone number was registered while verification was pending")
    user = User(
        id=str(uuid.uuid4()),
        name=pending.name,
        phone=pending.phone,
        email=pending.email,
        role=pending.role,
        location=pending.location,
        password_hash=pending.password_hash,
    )
    db.add(user)
    db.delete(pending)
    db.commit()

    token = create_access_token(data={"sub": user.id, "role": user.role})
    return {"message": "Email verified", "id": user.id, "name": user.name, "role": user.role, "access_token": token, "token_type": "bearer"}

